package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/google/uuid"
	"github.com/shrika/product-catalog-graphql-api/internal/graph/dataloader"
	"github.com/shrika/product-catalog-graphql-api/internal/graph/generated"
	"github.com/shrika/product-catalog-graphql-api/internal/graph/model"
	"github.com/shrika/product-catalog-graphql-api/internal/service"
	apperrors "github.com/shrika/product-catalog-graphql-api/pkg/errors"
)

// Products is the resolver for the products field.
func (r *categoryResolver) Products(ctx context.Context, obj *model.Category, limit *int, offset *int) ([]*model.Product, error) {
	categoryID, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, apperrors.InvalidArgument("category id is invalid")
	}

	resolvedLimit := 20
	if limit != nil {
		resolvedLimit = *limit
	}
	resolvedOffset := 0
	if offset != nil {
		resolvedOffset = *offset
	}

	products, err := r.ProductService.ListProductsByCategory(ctx, categoryID, resolvedLimit, resolvedOffset)
	if err != nil {
		return nil, err
	}
	return toGraphQLProducts(products), nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	product, err := r.ProductService.CreateProduct(ctx, service.CreateProductInput{
		Name:          input.Name,
		Description:   input.Description,
		Price:         input.Price,
		Currency:      input.Currency,
		CategoryID:    input.CategoryID,
		StockQuantity: input.StockQuantity,
	})
	if err != nil {
		return nil, err
	}
	return toGraphQLProduct(product), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (*model.Product, error) {
	product, err := r.ProductService.UpdateProduct(ctx, id, service.UpdateProductInput{
		Name:          input.Name,
		Description:   input.Description,
		Price:         input.Price,
		Currency:      input.Currency,
		CategoryID:    input.CategoryID,
		StockQuantity: input.StockQuantity,
	})
	if err != nil {
		return nil, err
	}
	return toGraphQLProduct(product), nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	return r.ProductService.DeleteProduct(ctx, id)
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.Category, error) {
	category, err := r.CategoryService.CreateCategory(ctx, service.CreateCategoryInput{Name: input.Name})
	if err != nil {
		return nil, err
	}
	return toGraphQLCategory(category), nil
}

// Category is the resolver for the category field.
func (r *productResolver) Category(ctx context.Context, obj *model.Product) (*model.Category, error) {
	if obj.Category != nil {
		return obj.Category, nil
	}

	loaders, ok := dataloader.For(ctx)
	if ok {
		thunk := loaders.CategoryByID.Load(ctx, obj.CategoryID)
		category, err := thunk()
		if err != nil {
			return nil, apperrors.Internal("failed loading category", err)
		}
		if category != nil {
			obj.Category = toGraphQLCategory(category)
			return obj.Category, nil
		}
	}

	category, err := r.CategoryService.GetCategory(ctx, obj.CategoryID)
	if err != nil {
		return nil, err
	}
	obj.Category = toGraphQLCategory(category)
	return obj.Category, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, filter *model.ProductFilterInput, pagination *model.PaginationInput, sorting *model.ProductSortInput) ([]*model.Product, error) {
	svcFilter := service.ProductFilter{
		Limit:     20,
		Offset:    0,
		SortBy:    "created_at",
		SortOrder: "DESC",
	}

	if filter != nil {
		svcFilter.MinPrice = filter.MinPrice
		svcFilter.MaxPrice = filter.MaxPrice
		svcFilter.CategoryID = filter.CategoryID
		svcFilter.NameSearch = filter.NameSearch
	}
	if pagination != nil {
		if pagination.Limit != nil {
			svcFilter.Limit = *pagination.Limit
		}
		if pagination.Offset != nil {
			svcFilter.Offset = *pagination.Offset
		}
	}
	if sorting != nil {
		if sorting.Field != nil {
			switch *sorting.Field {
			case model.ProductSortFieldName:
				svcFilter.SortBy = "name"
			case model.ProductSortFieldPrice:
				svcFilter.SortBy = "price"
			case model.ProductSortFieldUpdatedAt:
				svcFilter.SortBy = "updated_at"
			case model.ProductSortFieldStockQuantity:
				svcFilter.SortBy = "stock_quantity"
			default:
				svcFilter.SortBy = "created_at"
			}
		}
		if sorting.Order != nil {
			if *sorting.Order == model.SortOrderAsc {
				svcFilter.SortOrder = "ASC"
			} else {
				svcFilter.SortOrder = "DESC"
			}
		}
	}

	products, err := r.ProductService.ListProducts(ctx, svcFilter)
	if err != nil {
		return nil, err
	}
	return toGraphQLProducts(products), nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	product, err := r.ProductService.GetProduct(ctx, id)
	if err != nil {
		return nil, err
	}
	return toGraphQLProduct(product), nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	categories, err := r.CategoryService.ListCategories(ctx)
	if err != nil {
		return nil, err
	}
	return toGraphQLCategories(categories), nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*model.Category, error) {
	category, err := r.CategoryService.GetCategory(ctx, id)
	if err != nil {
		return nil, err
	}
	return toGraphQLCategory(category), nil
}

// Category returns generated.CategoryResolver implementation.
func (r *Resolver) Category() generated.CategoryResolver { return &categoryResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Product returns generated.ProductResolver implementation.
func (r *Resolver) Product() generated.ProductResolver { return &productResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type categoryResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
