// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Category struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"createdAt"`
	Products  []*Product `json:"products"`
}

type CreateCategoryInput struct {
	Name string `json:"name"`
}

type CreateProductInput struct {
	Name          string  `json:"name"`
	Description   *string `json:"description,omitempty"`
	Price         float64 `json:"price"`
	Currency      *string `json:"currency,omitempty"`
	CategoryID    string  `json:"categoryId"`
	StockQuantity int     `json:"stockQuantity"`
}

type Mutation struct {
}

type PaginationInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type Product struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	Description   *string   `json:"description,omitempty"`
	Price         float64   `json:"price"`
	Currency      string    `json:"currency"`
	CategoryID    string    `json:"categoryId"`
	Category      *Category `json:"category"`
	StockQuantity int       `json:"stockQuantity"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type ProductFilterInput struct {
	MinPrice   *float64 `json:"minPrice,omitempty"`
	MaxPrice   *float64 `json:"maxPrice,omitempty"`
	CategoryID *string  `json:"categoryId,omitempty"`
	NameSearch *string  `json:"nameSearch,omitempty"`
}

type ProductSortInput struct {
	Field *ProductSortField `json:"field,omitempty"`
	Order *SortOrder        `json:"order,omitempty"`
}

type Query struct {
}

type UpdateProductInput struct {
	Name          *string  `json:"name,omitempty"`
	Description   *string  `json:"description,omitempty"`
	Price         *float64 `json:"price,omitempty"`
	Currency      *string  `json:"currency,omitempty"`
	CategoryID    *string  `json:"categoryId,omitempty"`
	StockQuantity *int     `json:"stockQuantity,omitempty"`
}

type ProductSortField string

const (
	ProductSortFieldName          ProductSortField = "NAME"
	ProductSortFieldPrice         ProductSortField = "PRICE"
	ProductSortFieldCreatedAt     ProductSortField = "CREATED_AT"
	ProductSortFieldUpdatedAt     ProductSortField = "UPDATED_AT"
	ProductSortFieldStockQuantity ProductSortField = "STOCK_QUANTITY"
)

var AllProductSortField = []ProductSortField{
	ProductSortFieldName,
	ProductSortFieldPrice,
	ProductSortFieldCreatedAt,
	ProductSortFieldUpdatedAt,
	ProductSortFieldStockQuantity,
}

func (e ProductSortField) IsValid() bool {
	switch e {
	case ProductSortFieldName, ProductSortFieldPrice, ProductSortFieldCreatedAt, ProductSortFieldUpdatedAt, ProductSortFieldStockQuantity:
		return true
	}
	return false
}

func (e ProductSortField) String() string {
	return string(e)
}

func (e *ProductSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductSortField", str)
	}
	return nil
}

func (e ProductSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProductSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProductSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortOrder string

const (
	SortOrderAsc  SortOrder = "ASC"
	SortOrderDesc SortOrder = "DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
